@startuml
'https://plantuml.com/sequence-diagram


participant Loader
participant LoaderUI
participant CoreManager
participant InputManager
participant CastManager
participant SoundManager
participant ObjectPoolManager
participant EventManager
entity MainMenu
participant Player
participant Boss


Loader -> CoreManager : Initialize
CoreManager-> SoundManager :Initialize
CoreManager-> InputManager :Initialize
CoreManager-> ObjectPoolManager :Initialize
CoreManager-> EventManager :Initialize
CoreManager->CastManager:Initialize
MainMenu->Player:Instantiates
MainMenu->Boss:Instantiates
MainMenu->MainScene
Loader->LoaderUI: Updates





@enduml

